/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.graalvm.buildtools.native") version "0.10.1"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // MySQL Connector JAR dependency
    implementation("com.mysql:mysql-connector-j:8.4.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "MainSystem.Main"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

graalvmNative {
    binaries {
        named("main") {
            imageName.set("Project1App") // The name of your final executable
            mainClass.set("MainSystem.Main") // Points to your Main.java
            
            buildArgs.addAll(
                "--gui",                      // Required for Windows/macOS GUI apps
                "--no-fallback",              // Ensures a standalone binary is created
                "-H:+AddAllCharsets",         // Often needed for database drivers
                "--initialize-at-build-time=ConsoleSystem.ConsoleColors" // Optional optimization
            )

            buildArgs.addAll(
                "--gui",
                "--no-fallback",
                "-H:+AddAllCharsets",
                // Add this line to include the Icons directory in the native binary
                "-H:IncludeResources=Icons/.*" 
            )

            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(21)) // Match your project version
                vendor.set(JvmVendorSpec.GRAAL_VM)
            })
        }
    }
    metadataRepository {
        enabled.set(true)
    }
}

tasks.register("cleanRun") {
    group = "application"
    description = "Runs a clean build and then executes the application."
    dependsOn("clean") // Ensures the 'build' directory is deleted first
    finalizedBy("run") // Triggers the 'run' task after 'clean' completes
}