/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.graalvm.buildtools.native") version "0.10.3"

    id("java")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // MySQL Connector JAR dependency
    implementation("com.mysql:mysql-connector-j:8.4.0")

    // FlatLaf for modern Swing look and feel
    implementation("com.formdev:flatlaf:3.4.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass = "MainSystem.Main"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(21))
                vendor.set(JvmVendorSpec.GRAAL_VM)
            })

            // 2. Prevent GraalVM from "cleaning up" GUI methods during build
            buildArgs.add("--initialize-at-run-time=java.awt.Toolkit")
            buildArgs.add("--initialize-at-run-time=java.awt.Component")
            buildArgs.add("--initialize-at-run-time=javax.swing.UIManager")
            buildArgs.add("--initialize-at-run-time=javax.swing.Box")

            imageName.set("Project2App")
            mainClass.set("MainSystem.Main")

            // 1. Critical for Desktop apps: Allow AWT and Java Desktop components
            jvmArgs.add("-Djava.awt.headless=false")
            
            // 3. Include all character sets and locales for GUI rendering
            buildArgs.add("-H:+AddAllCharsets")
            buildArgs.add("-H:+IncludeAllLocales")
            
            // 4. Ensure metadata for reflection is included (Swing uses this heavily)
            buildArgs.add("-H:+UnlockExperimentalVMOptions")
            buildArgs.add("-H:+AddAllCharsets")

            if (org.gradle.internal.os.OperatingSystem.current().isWindows) {
                // Keep these commented out until the app opens successfully
                // buildArgs.add("-H:NativeLinkerOption=/SUBSYSTEM:WINDOWS")
                // buildArgs.add("-H:NativeLinkerOption=/ENTRY:mainCRTStartup")
            }
        }
    }
    metadataRepository {
        enabled.set(true)
    }
}

tasks.register("cleanRun") {
    group = "application"
    description = "Runs a clean build and then executes the application."
    dependsOn("clean") // Ensures the 'build' directory is deleted first
    finalizedBy("run") // Triggers the 'run' task after 'clean' completes
}